---
  - name: Init Swarm Master
    hosts: swarm_master_hosts
    gather_facts: True
    remote_user: "{{ default_user }}"
    tasks:
      - name: Ensure docker deamon is running
        service:
          name: docker
          state: started
        become: True

      - name: Swarm Init
        command: docker swarm init --advertise-addr {{ inventory_hostname }}

      - name: Get Worker Token
        command: docker swarm join-token worker -q
        register: worker_token

      - name: Show Worker Token
        debug: var=worker_token.stdout

      - name: Master Token
        command: docker swarm join-token manager -q
        register: master_token

      - name: Show Master Token
        debug: var=master_token.stdout

  - name: Join Swarm Cluster
    hosts: swarm_worker_hosts
    remote_user: "{{ default_user }}"
    gather_facts: False
    vars:
      token: "{{ hostvars[groups['swarm_master_hosts'][0]]['worker_token']['stdout'] }}"
      master: "{{ hostvars[groups['swarm_master_hosts'][0]]['ansible_default_ipv4']['address'] }}"
    tasks:
      - name: Ensure docker deamon is running
        service:
          name: docker
          state: started
        become: True

      - name: Join Swarm Cluster as a Worker
        command: docker swarm join --token {{ token }} {{ master }}:2377
        register: worker

      - name: Show Results
        debug: var=worker.stdout

      - name: Show Errors
        debug: var=worker.stderr
